//--Global Actions
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_SUBTITLE = 'UPDATE_SUBTITLE';
export const UPDATE_SELECTED_PAGE = 'UPDATE_SELECTED_PAGE';
export const UPDATE_SELECTED_PAGE_OPTIONS = 'UPDATE_SELECTED_PAGE_OPTIONS';
export const UPDATE_DRAWER = 'UPDATE_DRAWER';
export const UPDATE_DIALOG = 'UPDATE_DIALOG';
export const UPDATE_SNACKBAR = 'UPDATE_SNACKBAR';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_SEARCH_SUGGESTIONS = 'UPDATE_SEARCH_SUGGESTIONS';
export const SET_VISIBILITY_TITLEBAR = 'SET_VISIBILITY_TITLEBAR';
export const UPDATE_SELECTED_PROJECT_ID = 'UPDATE_SELECTED_PROJECT_ID';
export const UPDATE_SELECTED_TASKS = 'UPDATE_SELECTED_TASKS';


//--Projects Actions
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const COMPLETE_PROJECT = 'COMPLETE_PROJECT';



//--Tasks Actions
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const REMOVE_TASK = 'REMOVE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const TOOGLE_ALL = 'TOOGLE_ALL';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
